all:
	gcc -o process_monitor_query main.c proc_stat.c utils.c general_stat_query.c cpu_usage.c

debug:
	gcc -g -o process_monitor_query main.c proc_stat.c utils.c general_stat_query.c cpu_usage.c


clean:
	rm -f process_monitor_query
